name: my first pipeline

on:
    push: 
        branches: [ "main "]

jobs:
    built:
        runs-on: ubuntu-latest
        steps:
            - name: Clone the code
              uses: actions/checkout@va
            - name: Build image
              run:
                docker build -it mbipaddy/cicd-portfolio .
            - name: Docker login
              uses: docker/login-action@v3
              with:
                username: mbipaddy
                password: ${{ secrets.DOCKER_PASS}}
            - name: Push image
              run:
                docker push mbipaddy/cicd-portfolio






